[GOL-1149] Corrigir: Alarme só toca se celular estiver ligado na energia ou app aberto (maximizado), Android apenas
midia3/react-native-alarm-notification pull request #2
Opened 2022-12-06 14:46 UTC by josedomingos919

2022-12-06 21:55 UTC, tensfeld requested changes

2022-12-06 21:55 UTC, tensfeld commented on android/src/main/java/com/emekalites/react/alarm/notification/AlarmReceiver.java
> +                            alarmUtil.repeatAlarm(alarm);
Essa mesma linha precisa existir também no arquivo `AlarmDismissReceiver.java`, que é usado quando se faz o swipe para dispensar a notificação.

2022-12-07 05:42 UTC, josedomingos919 commented on android/src/main/java/com/emekalites/react/alarm/notification/AlarmReceiver.java
> +                            alarmUtil.repeatAlarm(alarm);
feito

2022-12-07 18:38 UTC, tensfeld approved these changes

2022-12-07 18:40 UTC, merged